@baseUrl = https://localhost:44343/


### ~~ QUESTION SETS ~~ ###
### Get all question sets
GET {{baseUrl}}question-sets HTTP/1.1


### Add question set
# @name  addQuestionSet
POST {{baseUrl}}question-sets HTTP/1.1
Content-Type: application/json

{
    "name": "New Question Set [{{$guid}}]",
    "description": "New Question Set Description that describe this question set.",
    "imageUrl": "",
    "color": "#FFFFFF"
}

@newQuestionSetId = {{addQuestionSet.response.headers.Location}}


### Get added question set
GET {{baseUrl}}question-sets/{{newQuestionSetId}} HTTP/1.1

### ~~ QUESTIONS ~~ ###
### Add question
# @name  addQuestion
POST {{baseUrl}}questions HTTP/1.1
Content-Type: application/json

{
  "text": "New question text [{{$guid}}]",
  "answers": [
    {
      "text": "Answer text 1",
      "isCorrect": true
    },
    {
      "text": "Answer text 2",
      "isCorrect": false
    },
    {
      "text": "Answer text 3",
      "isCorrect": false
    },
    {
      "text": "Answer text 4",
      "isCorrect": false
    }
  ],
  "questionSetId": "{{newQuestionSetId}}"
}

@newQuestionId = {{addQuestion.response.headers.Location}}


### Get added question
GET {{baseUrl}}questions/{{newQuestionId}} HTTP/1.1

### Delete added question
DELETE {{baseUrl}}questions/{{newQuestionId}} HTTP/1.1


### ~~ QUIZZES ~~ ###
### Generate quiz
# @name generateQuiz
POST {{baseUrl}}quizzes HTTP/1.1
Content-Type: application/json

{
  "questionSetId": "{{newQuestionSetId}}",
  "questionCount": 2
}

@newQuizId = {{generateQuiz.response.headers.Location}}


### Get added quiz
# @name getGenerateQuiz
GET {{baseUrl}}quizzes/{{newQuizId}} HTTP/1.1

@questionIdFromQuiz = {{getGenerateQuiz.response.body.questions[0].id}}
@answerIdFromQuiz = {{getGenerateQuiz.response.body.questions[0].answers[0].id}}

### Get solve added quiz
PUT {{baseUrl}}quizzes/{{newQuizId}} HTTP/1.1
Content-Type: application/json

{
  "playerAnswers": [
    {
      "questionId": "{{questionIdFromQuiz}}",
      "answerId": "{{answerIdFromQuiz}}"
    }
  ]
}

### Get quiz summary
GET {{baseUrl}}quizzes/{{newQuizId}}/summary HTTP/1.1
